CREATE TABLE GALAXIA(
 COD INT PRIMARY KEY,
 NOME VARCHAR(60),
 TIPO VARCHAR(60)
)

CREATE TABLE ESTRELA (
 COD INT PRIMARY KEY,
 NOME VARCHAR(60),
 TIPO VARCHAR(60),
 GALAXIA INT
)

CREATE TABLE PLANETA (
 COD INT PRIMARY KEY,
 NOME VARCHAR(60),
 HABITAVEL BOOL,
 ESTRELA INT
)